#!/bin/bash

# Elith Global Installation Script
# Installs both the Python CLI wrapper and TypeScript TUI globally

set -e

echo "🚀 Installing Elith globally..."
echo ""

# Get the absolute path to the project directory
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Step 1: Install TypeScript TUI globally
echo "📦 Step 1/2: Installing TypeScript TUI..."
cd "$PROJECT_DIR/tui"

if [ ! -d "node_modules" ]; then
    echo "   Installing npm dependencies..."
    npm install
fi

echo "   Building TypeScript..."
npm run build

echo "   Creating global symlink..."
npm link

echo "   ✅ TypeScript TUI installed as 'elith-tui'"
echo ""

# Step 2: Install Python CLI wrapper
echo "📦 Step 2/2: Installing Python CLI wrapper..."
cd "$PROJECT_DIR"

INSTALL_PATH="/usr/local/bin/elith"

# Check if we need sudo
if [ -w "/usr/local/bin" ]; then
    SUDO=""
else
    SUDO="sudo"
    echo "   📝 Note: sudo access required to install to /usr/local/bin"
fi

# Create the wrapper script
cat > /tmp/elith << EOF
#!/bin/bash
# Elith CLI wrapper script
# Auto-generated by global-install.sh

PROJECT_DIR="$PROJECT_DIR"

# Activate virtual environment if it exists
if [ -f "\$PROJECT_DIR/venv/bin/activate" ]; then
    source "\$PROJECT_DIR/venv/bin/activate"
fi

# Run the CLI (which will launch the TypeScript TUI)
python3 "\$PROJECT_DIR/cli.py" "\$@"
EOF

# Install the wrapper
$SUDO mv /tmp/elith "$INSTALL_PATH"
$SUDO chmod +x "$INSTALL_PATH"

echo "   ✅ Python CLI wrapper installed as 'elith'"
echo ""

# Success message
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Installation complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You can now run Elith from anywhere using either:"
echo ""
echo "  elith                     # Launch TUI (default)"
echo "  elith-tui                 # Launch TUI directly"
echo "  elith --help              # Show help"
echo "  elith explain .           # Explain repository"
echo "  elith architect --problem 'auth system'  # Generate proposals"
echo "  elith refactor src/app.py # Refactor a file"
echo "  elith test-gen src/utils.py  # Generate tests"
echo "  elith models              # List available models"
echo ""
echo "To uninstall:"
echo "  npm unlink -g elith-tui   # Remove TypeScript TUI"
echo "  sudo rm /usr/local/bin/elith  # Remove Python CLI wrapper"
echo ""

# Made with Bob