#!/bin/bash
# Elith CLI Installation Script
# This creates a global 'elith' command

set -e

echo "🚀 Installing Elith CLI..."

# Get the absolute path to the project directory
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Create a wrapper script in /usr/local/bin
INSTALL_PATH="/usr/local/bin/elith"

# Check if we need sudo
if [ -w "/usr/local/bin" ]; then
    SUDO=""
else
    SUDO="sudo"
    echo "📝 Note: sudo access required to install to /usr/local/bin"
fi

# Create the wrapper script
cat > /tmp/elith << EOF
#!/bin/bash
# Elith CLI wrapper script
# Auto-generated by install.sh

PROJECT_DIR="$PROJECT_DIR"

# Activate virtual environment if it exists
if [ -f "\$PROJECT_DIR/venv/bin/activate" ]; then
    source "\$PROJECT_DIR/venv/bin/activate"
fi

# Run the CLI
python3 "\$PROJECT_DIR/cli.py" "\$@"
EOF

# Install the wrapper
$SUDO mv /tmp/elith "$INSTALL_PATH"
$SUDO chmod +x "$INSTALL_PATH"

echo "✅ Elith CLI installed successfully!"
echo ""
echo "You can now use 'elith' from anywhere:"
echo ""
echo "  elith                     # Launch interactive TUI (default)"
echo "  elith --help              # Show help"
echo "  elith explain .           # Explain repository"
echo "  elith architect --problem 'auth system'  # Generate proposals"
echo "  elith refactor src/app.py # Refactor a file"
echo "  elith test-gen src/utils.py  # Generate tests"
echo "  elith models              # List available models"
echo ""

# Made with Bob
