"""Session logger for Bob reports."""
from pathlib import Path
from datetime import datetime
from ..models.session import Session


class SessionLogger:
    """Logs sessions to bob-reports directory."""
    
    def __init__(self, reports_dir: str = "bob-reports"):
        """Initialize logger with reports directory."""
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(exist_ok=True)
        (self.reports_dir / ".gitkeep").touch()
    
    def log_session(self, session: Session) -> str:
        """
        Log session to markdown file.
        
        Returns path to created report file.
        """
        timestamp = session.created_at.strftime("%Y%m%d_%H%M%S")
        filename = f"session_{timestamp}_{session.session_id[:8]}.md"
        filepath = self.reports_dir / filename
        
        content = self._build_report(session)
        filepath.write_text(content, encoding='utf-8')
        
        return str(filepath)
    
    def _build_report(self, session: Session) -> str:
        """Build markdown report content."""
        lines = [
            "# Elith Session Report",
            "",
            f"**Session ID:** {session.session_id}",
            f"**Model:** {session.model}",
            f"**Operation:** {session.operation}",
            f"**Status:** {session.status.value}",
            f"**Created:** {session.created_at.isoformat()}",
        ]
        
        if session.completed_at:
            lines.append(f"**Completed:** {session.completed_at.isoformat()}")
        
        lines.extend([
            "",
            "## Repository",
            f"{session.repo_path}",
            ""
        ])
        
        if session.vault_path:
            lines.extend([
                "## Vault",
                f"{session.vault_path}",
                ""
            ])
        
        if session.files_changed:
            lines.extend([
                "## Files Changed",
                ""
            ])
            for file in session.files_changed:
                lines.append(f"- {file}")
            lines.append("")
        
        lines.extend([
            "## Output",
            "```",
            session.output,
            "```",
            "",
            "---",
            "*Generated by Elith*"
        ])
        
        return "\n".join(lines)


# Global logger instance
logger = SessionLogger()

# Made with Bob
